export const DISPLAY_SIDEBAR = "DISPLAY_SIDEBAR";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_INCOME_BEGIN = "CREATE_INCOME_BEGIN";
export const CREATE_INCOME_SUCCESS = "CREATE_INCOME_SUCCESS";
export const CREATE_INCOME_ERROR = "CREATE_INCOME_ERROR";

export const GET_INCOMES_BEGIN = "GET_INCOMES_BEGIN";

export const DELETE_INCOME_BEGIN = "DELETE_INCOME_BEGIN";

export const CREATE_TRANSACTION_BEGIN = "CREATE_TRANSACTION_BEGIN";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_ERROR = "CREATE_TRANSACTION_ERROR";

export const GET_TRANSACTIONS_BEGIN = "GET_TRANSACTIONS_BEGIN";
export const GET_INCOMES_SUCCESS = "GET_INCOMES_SUCCESS";
export const GET_EXPENSES_SUCCESS = "GET_EXPENSES_SUCCESS";

export const DELETE_TRANSACTION_BEGIN = "DELETE_TRANSACTION_BEGIN";

export const CHANGE_PAGE_INCOME = "CHANGE_PAGE_INCOME";
export const CHANGE_PAGE_EXPENSE = "CHANGE_PAGE_EXPENSE";
